
version: '3.9'
services:
  rasa:
    build:
      context: ./rasa
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command: rasa run --enable-api --cors "*"

  actions:
    build:
      context: ./rasa
      dockerfile: Dockerfile.actions
    volumes:
      - ./rasa/actions:/app/actions
    ports:
      - "5055:5055"

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - rasa
      - actions
