# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit app code into the container
COPY . .
COPY ./requirements.txt /app

# Install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt
# Expose the default Streamlit port
EXPOSE 8501

# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
